version: '3'
services:

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: "wisebox"
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_GB.UTF-8"
      POSTGRES_PASSWORD:
    volumes:
      - ./postgres-init.d:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DJANGO_ADMIN_USER:
      DJANGO_ADMIN_EMAIL:
      DJANGO_ADMIN_PASSWORD:
      DJANGO_DEBUG:
      DJANGO_LANGUAGE_CODE:
      DJANGO_SECRET_KEY:
      DJANGO_SITE_NAME:
      POSTGRES_PASSWORD:

volumes:
  postgres-data:
