# Generated by Django 3.0.6 on 2020-06-05 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('interval', models.PositiveIntegerField()),
                ('frequency', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BucketMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BucketRssi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['name'], name='dataserver__name_ed1444_idx'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dataserver.Organisation'),
        ),
        migrations.AddField(
            model_name='bucketrssi',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rssis', to='dataserver.Bucket'),
        ),
        migrations.AddField(
            model_name='bucketmetadata',
            name='buckets',
            field=models.ManyToManyField(related_name='metadata', to='dataserver.Bucket'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='dataserver.Device'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dataserver.Timezone'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataserver.Organisation'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['name'], name='dataserver__name_d23069_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac'], name='dataserver__mac_c1e94c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('mac', 'organisation')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='dataserver__key_ea9c08_idx'),
        ),
    ]
