# Generated by Django 3.0.6 on 2020-06-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.PositiveSmallIntegerField()),
                ('start_time', models.DateTimeField()),
                ('interval', models.PositiveIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('users', models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dataserver.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='BucketRssi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.SmallIntegerField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rssis', to='dataserver.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='BucketMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('buckets', models.ManyToManyField(related_name='metadata', to='dataserver.Bucket')),
            ],
        ),
        migrations.AddField(
            model_name='bucket',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='dataserver.Device'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dataserver.Timezone'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataserver.Organisation')),
            ],
        ),
    ]
