# Generated by Django 3.0.6 on 2020-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0002_auto_20200605_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
